# Generated by Django 5.2.6 on 2025-09-17 23:14

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeFileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('themeId', models.CharField(max_length=255)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('contentType', models.CharField(max_length=64)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.shopifysite')),
            ],
            options={
                'db_table': 'themeFileUpload',
            },
        ),
        migrations.CreateModel(
            name='ThemeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder', models.CharField(db_index=True, max_length=255)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('contents', models.TextField(default='')),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('contentType', models.CharField(max_length=128)),
                ('uploads', models.ManyToManyField(to='themes.themefileupload')),
            ],
            options={
                'db_table': 'themeFile',
            },
        ),
    ]
