# Generated by Django 4.2.24 on 2025-09-25 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Dawn', max_length=255)),
            ],
            options={
                'db_table': 'themeCollection',
            },
        ),
        migrations.CreateModel(
            name='ThemeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder', models.CharField(db_index=True, max_length=255)),
                ('fileName', models.CharField(db_index=True, max_length=255)),
                ('contents', models.TextField(default='')),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('contentType', models.CharField(max_length=128)),
                ('binaryFile', models.BooleanField(default=False, null=True)),
                ('collection', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='themes.themecollection')),
            ],
            options={
                'db_table': 'themeFile',
            },
        ),
    ]
