# Generated by Django 5.2.6 on 2025-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themefile',
            name='binaryFile',
            field=models.BooleanField(default=False),
        ),
    ]
