# Generated by Django 5.2.6 on 2025-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_themefile_binaryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themefile',
            name='binaryFile',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
