# Generated by Django 5.2.6 on 2025-09-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_alter_themefile_binaryfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themefile',
            old_name='path',
            new_name='fileName',
        ),
    ]
