# Generated by Django 5.2.6 on 2025-09-19 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_rename_path_themefile_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Dawn', max_length=255)),
            ],
            options={
                'db_table': 'themeCollection',
            },
        ),
    ]
