# Generated by Django 5.2.6 on 2025-09-19 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_themecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='themefile',
            name='collection',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='themes.themecollection'),
        ),
    ]
