# Generated by Django 5.2.6 on 2025-09-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_themefile_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themefile',
            name='collection',
        ),
    ]
