# Generated by Django 5.2.6 on 2025-09-19 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_remove_themefile_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='themecollection',
            name='files',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='themes.themefile'),
        ),
    ]
