# Generated by Django 5.2.6 on 2025-09-19 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_themecollection_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themecollection',
            name='files',
        ),
        migrations.AddField(
            model_name='themefile',
            name='collection',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='themes.themecollection'),
        ),
    ]
