# Generated by Django 5.2.6 on 2025-09-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_remove_themecollection_files_themefile_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themefile',
            name='uploads',
        ),
        migrations.DeleteModel(
            name='ThemeFileUpload',
        ),
    ]
