# Generated by Django 4.2.24 on 2025-09-25 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppScopes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scopeName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'required_scopes',
            },
            bases=(models.Model, home.models.IdAware),
        ),
        migrations.CreateModel(
            name='ShopifySite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=255)),
                ('shopDomain', models.CharField(db_index=True, max_length=128)),
                ('authToken', models.CharField(max_length=255)),
                ('contactEmail', models.EmailField(default='email@email.com', max_length=254, null=True)),
                ('contactName', models.TextField(default='', null=True)),
                ('shopUrl', models.TextField(default='', null=True)),
                ('appKey', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shopify_site',
            },
            bases=(models.Model, home.models.IdAware),
        ),
        migrations.CreateModel(
            name='ThemeFileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('themeId', models.CharField(max_length=255)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('contentType', models.CharField(max_length=64)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.shopifysite')),
            ],
            options={
                'db_table': 'themeFileUpload',
            },
        ),
    ]
