# Generated by Django 5.2.6 on 2025-09-17 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppScopes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scopeName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'required_scopes',
            },
        ),
        migrations.CreateModel(
            name='ShopifySite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shopName', models.CharField(max_length=255)),
                ('shopDomain', models.CharField(db_index=True, max_length=128)),
                ('authToken', models.CharField(max_length=255)),
                ('appKey', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shopify_site',
            },
        ),
    ]
