# Generated by Django 5.2.6 on 2025-09-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysite',
            name='contactEmail',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='shopifysite',
            name='contactName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shopifysite',
            name='shopUrl',
            field=models.TextField(default=''),
        ),
    ]
