# Generated by Django 5.2.6 on 2025-09-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0002_shopifysite_contactemail_shopifysite_contactname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysite',
            name='contactEmail',
            field=models.EmailField(default='email@email.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shopifysite',
            name='contactName',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='shopifysite',
            name='shopUrl',
            field=models.TextField(default='', null=True),
        ),
    ]
