# Generated by Django 5.2.6 on 2025-09-24 20:35

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0003_alter_shopifysite_contactemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeFileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('themeId', models.CharField(max_length=255)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('contentType', models.CharField(max_length=64)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.shopifysite')),
            ],
            options={
                'db_table': 'themeFileUpload',
            },
        ),
    ]
