# Generated by Django 4.2.24 on 2025-09-25 22:03

from django.db import migrations, models
import home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteNav',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(default='/', max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('displayOrder', models.IntegerField(default=99999999)),
            ],
            options={
                'db_table': 'sitenav',
            },
            bases=(models.Model, home.models.IdAware),
        ),
    ]
