# Generated by Django 5.2.6 on 2025-09-18 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNav',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=64)),
                ('url', models.CharField(default='/', max_length=255)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sitenav',
            },
        ),
    ]
