# Generated by Django 5.2.6 on 2025-09-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sitenav'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenav',
            name='displayOrder',
            field=models.IntegerField(default=99999999),
        ),
    ]
