# Generated by Django 5.2.6 on 2025-09-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitenav_displayorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitenav',
            name='permission',
        ),
    ]
