# Generated by Django 4.2.24 on 2025-09-25 22:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'user_permission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='No Name')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('permissions', models.ManyToManyField(to='ywm_auth.userpermissions')),
            ],
            options={
                'db_table': 'ywm_user',
            },
        ),
        migrations.CreateModel(
            name='AuthRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('expires', models.DateTimeField()),
                ('requestUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ywm_auth.user')),
            ],
            options={
                'db_table': 'auth_request',
            },
        ),
    ]
