# Generated by Django 5.2.6 on 2025-09-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ywm_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
